<h1>Maze Solver

Creating a Training an agent using Q-Learning to help it move around in a maze(shown below).


![alt text](<Maze_Pic-1.png>)

In [13]:
#Importing the library
import numpy as np


In [14]:
#Setting parameters (alpha[learning rate] and gamma[discount factor])
alpha=0.9

gamma=0.75


In [15]:
#Defining states
locations_to_states= {
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6,
    'H':7,
    'I':8,
    'J':9,
    'K':10,
    'L':11
}

#Defining actions
actions=[0,1,2,3,4,5,6,7,8,9,10,11]


In [16]:
#Defining the rewards
rewards= np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
                   [1,0,1,0,0,1,0,0,0,0,0,0],
                   [0,1,0,0,0,0,1,0,0,0,0,0],
                   [0,0,0,0,0,0,0,1,0,0,0,0],
                   [0,0,0,0,0,0,0,0,1,0,0,0],
                   [0,1,0,0,0,0,0,0,0,1,0,0],
                   [0,0,1,0,0,0,100,1,0,0,0,0],
                   [0,0,0,1,0,0,1,0,0,0,0,1],
                   [0,0,0,0,1,0,0,0,0,1,0,0],
                   [0,0,0,0,0,1,0,0,1,0,1,0],
                   [0,0,0,0,0,0,0,0,0,1,0,1],
                   [0,0,0,0,0,0,0,1,0,0,1,0]])


In [17]:

#Initializing the Q-values
Q=np.array(np.zeros([12,12]))

#Implementing the Q-learning process
for i in range(1000):
    current_state= np.random.randint(0,12)
    playable_actions= []

    for j in range(12):
        if rewards[current_state,j] > 0:
            playable_actions.append(j)

    next_state= np.random.choice(playable_actions)
    #Temporal Difference(TD)
    TD= rewards[current_state, next_state] + gamma*Q[next_state, np.argmax(Q[next_state, ])] - Q[current_state, next_state]

    Q[current_state, next_state]= Q[current_state, next_state] + alpha * TD

#checking the Q-matrix
print("Q-Values:")
print(Q.astype(int))


Q-Values:
[[  0 170   0   0   0   0   0   0   0   0   0   0]
 [128   0 226   0   0 129   0   0   0   0   0   0]
 [  0 170   0   0   0   0 300   0   0   0   0   0]
 [  0   0   0   0   0   0   0 226   0   0   0   0]
 [  0   0   0   0   0   0   0   0  74   0   0   0]
 [  0 170   0   0   0   0   0   0   0  97   0   0]
 [  0   0 226   0   0   0 399 226   0   0   0   0]
 [  0   0   0 170   0   0 300   0   0   0   0 170]
 [  0   0   0   0  56   0   0   0   0  97   0   0]
 [  0   0   0   0   0 128   0   0  74   0 128   0]
 [  0   0   0   0   0   0   0   0   0  97   0 170]
 [  0   0   0   0   0   0   0 226   0   0 128   0]]


In [18]:
#Making a mapping from states to the locations

state_to_location= {state: location for location, state in locations_to_states.items()}
def route(starting_location, ending_location):
    route=[starting_location]
    next_location= starting_location
    while (next_location != ending_location):
        starting_state= locations_to_states[starting_location]
        next_state= np.argmax(Q[starting_state, ])
        next_location= state_to_location[next_state]
        route.append(next_location)
        starting_location= next_location
    return route


In [19]:

print('Route:')
route('E', 'G')

Route:


['E', 'I', 'J', 'F', 'B', 'C', 'G']

<h2>Improved Version of the Above method

Adding automatic reward distribution to make agent tmove to any desired block in the system

In [ ]:
#Defining the rewards (second time)
rewards= np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
                   [1,0,1,0,0,1,0,0,0,0,0,0],
                   [0,1,0,0,0,0,1,0,0,0,0,0],
                   [0,0,0,0,0,0,0,1,0,0,0,0],
                   [0,0,0,0,0,0,0,0,1,0,0,0],
                   [0,1,0,0,0,0,0,0,0,1,0,0],
                   [0,0,1,0,0,0,1,1,0,0,0,0],
                   [0,0,0,1,0,0,1,0,0,0,0,1],
                   [0,0,0,0,1,0,0,0,0,1,0,0],
                   [0,0,0,0,0,1,0,0,1,0,1,0],
                   [0,0,0,0,0,0,0,0,0,1,0,1],
                   [0,0,0,0,0,0,0,1,0,0,1,0]])


In [ ]:

def route_imporoved(starting_location, ending_location):
    rewards_new=np.copy(rewards)
    ending_state=locations_to_states[ending_location]
    rewards_new[ending_state, ending_state]= 1000
    Q=np.array(np.zeros([12, 12]))

    for i in range(1000):
        current_state= np.random.randint(0, 12)
        playable_actions=[]

        for j in range(12):
            if rewards_new[current_state, j] > 0:
                playable_actions.append(j)
        
        next_state= np.random.choice(playable_actions)
        TD= rewards_new[current_state, next_state] +  gamma * Q[next_state, np.argmax(Q[next_state, ])] - Q[current_state, next_state]
        Q[current_state, next_state]= Q[current_state, next_state] + alpha * TD

    route = [starting_location]
    next_location= starting_location

    while (next_location != ending_location):
        starting_state= locations_to_states[starting_location]
        next_state= np.argmax(Q[starting_state, ])
        next_location= state_to_location[next_state]
        route.append(next_location)
        starting_location= next_location
    return route


In [ ]:

print("Route:")
route_imporoved('E', 'D')



Adding an intermediary state to make agent pass through the certan block before reaching the end goal


In [ ]:

def best_route(starting_location, intermediary_location, ending_location):
    return route_imporoved(starting_location, intermediary_location) + route_imporoved(intermediary_location, ending_location)[1:]
best_route('E', 'F', 'D')

Working:  
#The program trains an agent to pass through a maze using Q learning. 
 
#Though Q learning is the easier side of reinforcement learning and is most effective in stochastic environments. However it struggles if state and action spaces are too large (also known as curse of dimensionality).